logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.atomicnorth.hrm: DEBUG

spring:
  application:
    name: HRManagement

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  jpa:
    open-in-view: false
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false

server:
  port: 8080

application:
  datasource:
#      id: ${DB_ID}
#      name: ${DB_NAME}
#      url: ${DB_URL}
#      username: ${DB_USERNAME}
#      password: ${DB_PASSWORD}

  clientApp:
    name: HRManagement

  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100

  cors:
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200,http://103.174.54.24:85,http://emanager-saas-dev.supraesapp.com:8080'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${application.clientApp.name}-alert,X-${application.clientApp.name}-error,X-${application.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512

translation:
  upload-translation-path: "/opt/emanager-uat/tomcat9/emsaasuat/ROOT/assets/json/EMSaaSTranslationData/json"

resume:
  server-upload-dir: ../emsaasuat/ROOT/assets/resume  # Path for storing resumes on the server
  local-upload-dir: bin/src/main/resources/assets/resume

resumeFileUrl:
  base-url: http://localhost:8080 # Local base URL
  global-base-url: http://emanager-saas-dev.supraesapp.com:8080/hr-management
